version: "3"

services:
  web:
    container_name: "portfolio_app"
    build: .
    ports:
      - "80:80"
      - "8080:8080"
      - "5173:5173"
      - "443:443"
    networks:
      portfolio_network:
        ipv4_address: 192.168.154.55
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  portfolio_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.154.0/24